services:
  - type: web
    name: freshers-backend
    runtime: python
    plan: free
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn --worker-class eventlet -w 1 --bind 0.0.0.0:$PORT run:app
    envVars:
      - key: DATABASE_URL
        sync: false
      - key: JWT_SECRET
        sync: false
      - key: CLOUDINARY_URL
        sync: false
      - key: FLASK_ENV
        value: production
      - key: PYTHON_VERSION
        value: 3.12.0
